version: '3.2'

volumes:
  mysql_data:
    driver: local

networks:
  n8n:

services:
  banco:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=n8n
      - MYSQL_PASSWORD=n8n
    networks:
      - n8n

  n8n:
    image: n8nio/n8n:1.1.1
    volumes:
      - ./.n8n:/home/node/.n8n
    ports:
      - ${N8N_PORT:-5678}:5678
    depends_on:
      - banco
    networks:
      - n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-n8n}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-n8n}
      - DB_TYPE=${DB_TYPE:-mysqldb}
      - DB_MYSQLDB_DATABASE=${DB_MYSQLDB_DATABASE:-n8n}
      - DB_MYSQLDB_HOST=${DB_MYSQLDB_HOST:-banco}
      - DB_MYSQLDB_PORT=${DB_MYSQLDB_PORT:-3306}
      - DB_MYSQLDB_USER=${DB_MYSQLDB_USER:-n8n}
      - DB_MYSQLDB_PASSWORD=${DB_MYSQLDB_PASSWORD:-n8n_n8n}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-AMERICA/Sao_Paulo}"
      - TZ=${TZ:-AMERICA/Sao_Paulo}"